### ISSUE TITLE
Service Support: Youtube Live

### ISSUE THREAD

**Issue by t2t2** [t2t2/livehub#3]

**Comment by vincent404** [comment]
Getting some issues when utilizing the API. Not exactly sure what the error number is, but its in the 4xx type. I have set the API key and have placed in the youtube channel id. Could we add a feature for debugging to see what error comes up or at least output to the user when we get an error code? Also, trying to learn fix.

**Comment by t2t2** [comment]
check the error logs: tail -f storage/logs/laravel-<date>.log
